<?php
include APP_PATH . "/views/header1.phtml";
?>
<div class="container">
    <div class="row justify-content-center align-items-center m-5">
        <h4 class="text-center p-0  display-4 border-bottom" style="margin-top:30px;">Welcome to My Page</h4>
        <div class="col-md-6" style="width: 40%;">
            <div class="p-3 card">
                <div class="d-flex justify-content-center align-items-center p-3 music border-bottom">
                    <div class="col-md-6">
                        <a href="<?php echo URLROOT ?>app/user/login" class="btn btn-danger">Login</a>
                    </div>
                    <div class="col-md-6">
                        <a href="<?php echo URLROOT ?>app/user/signup" class="btn btn-danger">Signup</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>