<?php
include APP_PATH . "/views/header1.phtml";
?>
<div class="container">
    <div class="row cant d-flex justify-content-center align-items-center">
        <h4 class="text-center p-0  display-4 border-bottom" style="margin-top:30px;">Create Web Hook</h4>
        <div class="col-md-6" style="width: 40%;">
            <div class="p-3 card">
                <div class="d-flex justify-content-center align-items-center p-3 music border-bottom">
                    <?php echo $this->tag->form(['method' => 'POST']); ?>

                    <div>
                        <label for="floatingInput">Web Hook Name:
                            <?php echo $this->tag->textField(["name", "id" => "floatingInput", "class" => "form-control", "required" => "true",]); ?>
                        </label>
                    </div>
                    <div>
                        <label for="floatingInput">URL:
                            <?php echo $this->tag->textField(["url", "id" => "floatingInput", "class" => "form-control", "required" => "true",]); ?>
                        </label>
                    </div>

                    <div>
                        <label for="inputtext" class="form-label">Events</label>
                        <select class="form-control selectedoption" name="event">
                            <option selected hidden disabled>Choose Any One</option>
                            <option value="add">Product Create</option>
                            <option value="update">Product Update</option>
                        </select>
                    </div>

                    <label for="floatingPassword">Authorization Key:
                        <?php echo $this->tag->textField(["key", "id" => "floatingpassword", "class" => "form-control", "required" => "true",]); ?>
                    </label>

                    <div>
                        <?php echo $this->tag->submitButton([
                            "Create",
                            "class" => "btn btn-danger",
                            "name" => "submit"
                        ]); ?>

                    </div>
                    </form>
                </div>


                <?php if (isset($success)) { ?>
                    <div class="alert alert-<?php echo $success === true ? 'success' : 'danger'; ?>" style="width: 100%;" <?php echo isset($success) === true ? '' : 'hidden'; ?>>
                        <?php echo $message;
                        ?>
                    <?php } ?>
                    </div>
            </div>
        </div>

    </div>