<?php
include APP_PATH."/views/header.phtml";
?>
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 vh-100">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center 
        pt-3 pb-2 mb-3 border-bottom">
          <h1 class="h2">All Products</h1>
        </div>

        <h2>Section title</h2>
        <div class="table-responsive">
            <?php
            
            $html = "";
            $html .= '<table id="myTable" class="table table-striped table-sm">     
        <tr>
          <th scope="col"> Product Name</th>
          <th scope="col">Product Category</th>
          <th scope="col">Price</th>
          <th scope="col">Stock</th>
        </tr>
      ';
            foreach ($data as $k => $v) {
                $html .= '<tr>
        <td>' . $v["name"] . '</td>
        <td>' . $v["category"] . '</td>
        <td>' . $v["price"] . '</td>
        <td>' . $v["stock"] . '</td>
        </tr>';
            }
            $html .= '</table>';
            echo $html;

            ?>
          </div>
                <br>

        </div>
      </main>
    </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <script src="../../../public/assets/js/ajax.js"></script>
  <script>
    $(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    // console.log(value);
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
$(function () {
    $("body").on("click","#submit1",function () {
        alert("Are you sure?");
    });
});
  </script>
</body>

</html>