<?php
include APP_PATH."/views/header.phtml";
?>
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 vh-100">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center 
        pt-3 pb-2 mb-3 border-bottom">
          <h1 class="h2">All Orders</h1>
        </div>

        <h2>Section title</h2>
        <div class="table-responsive">
            <?php
            
            $html = "";
            $html .= '<table id="myTable" class="table table-striped table-sm">     
        <tr>
          <th scope="col">Product Id</th>
          <th scope="col">Customer Email</th>
          <th scope="col">Status</th>
          <th scope="col">Quantity</th>
          <th scope="col">Date</th>
          <th scope="col">Change Status</th>
        </tr>
      ';
            foreach ($data as $k => $v) {
                $html .= '<tr>
        <td>' . $v["product_id"] . '</td>
        <td>' . $v["customer email"] . '</td>
        <td>' . $v["status"] . '</td>
        <td>' . $v["quantity"] . '</td>
        <td>' . $v["date"] . '</td>
        <td><form method ="post">
        <input type="hidden" name="id" value="'.$v["_id"].'"></input>
        <select class="form-control" name="filter">
        <option selected hidden disabled>Filter By Status</option>
        <option>Paid</option>
        <option>Processing</option>
        <option>Dispatched</option>
        <option>Shipped</option>
        <option>Refunded</option>
    </select><button type="submit" name="submit" class="btn btn-danger">Submit</button></form>
    </td>
        </tr>';
            }
            $html .= '</table>';
            echo $html;

            ?>
          </div>
                <br>

        </div>
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Quick View</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <h2>Product All Details:</h2>
                        <hr />
                        <h4 id="product-name"></h4>
                        <h4 id="category-name"></h4>
                        <h4 id="price"></h4>
                        <h4 id="stock"></h4>
                        <h4 id="variations"></h4>
</div>
      </main>
    </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <script src="../../../public/assets/js/ajax.js"></script>
  <script>
    $(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    // console.log(value);
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
$(function () {
    $("body").on("click","#submit1",function () {
        alert("Are you sure?");
    });
});
  </script>
</body>

</html>