<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.88.1">
  <title>Dashboard Template · Bootstrap v5.1</title>
<link rel="stylesheet" href="./../../public/assets/css/style.css">
  <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/dashboard/">



  <!-- Bootstrap core CSS -->
  <link href="../node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">


  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    main {
      /* background-image: url("../../../public/images/images.jpeg"); */
      background: rgb(196, 130, 159);
      background: radial-gradient(circle, rgba(196, 130, 159, 0.7679446778711485) 31%, rgba(148, 187, 233, 1) 100%);
      background-repeat: no-repeat;
      background-size: cover;
      color: white;
    }}

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>


  <!-- Custom styles for this template -->
  <link href="<?php echo URLROOT ?>assets/css/dashboard.css" rel="stylesheet">
</head>

<body>