<?php
include APP_PATH."/views/header.phtml";
?>
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center 
        pt-3 pb-2 mb-3 border-bottom">
          <h1 class="h2">All Products</h1>
        </div>

        <h2>Section title</h2>
        <div class="table-responsive">
            <?php
            
            $html = "";
            $html .= '<table id="myTable" class="table table-striped table-sm">     
        <tr>
          <th scope="col">Order Id</th>
          <th scope="col">Customer Name</th>
          <th scope="col">Customer Address</th>
          <th scope="col">Zipcode</th>
          <th scope="col">Product</th>
          <th scope="col">Quantity</th>
          <th scope="col">Update</th>
          <th scope="col">Delete</th>
        </tr>
      
      ';
            foreach ($data as $k => $v) {
                $html .= '<tr>
        <td>' . $v->order_id . '</td>
        <td>' . $v->customer_name . '</td>
        <td>' . $v->customer_address . '</td>
        <td>' . $v->zipcode . '</td>
        <td>' . $v->product . '</td>
        <td>' . $v->quantity . '</td>
        <td><a href = "'.URLROOT.'order/updateOrder?id='.$v->order_id.'" class="btn btn-primary">Edit</a></td>
        <td><form action="" method="POST">
        <input type="hidden" name="id" value="' . $v->order_id . '">
        <button type="submit" name="delete" class="userEdit btn btn-danger">Delete</button>
        </form></td>
        </tr>';
            }
            $html .= '</table>';
            echo $html;

            ?>
          </div>

        </div>
      </main>
    </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="../node_modules/bootstrap/dist/js/bootstrap.bundle.js" 
  integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" 
  crossorigin="anonymous"></script>
  <script>
    $(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    // console.log(value);
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
$(function () {
    $("body").on("click","#submit1",function () {
        alert("Are you sure?");
    });
});
  </script>
</body>

</html>